server {
    listen 80;
    listen [::]:80;
    server_name iu-hd.polyhydragames.com localhost _;

    server_tokens off;
    root /srv/site;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
